### ISSUE TITLE
ERROR: extra keys not allowed @ data['mqtt']['discovery_prefix']

### ISSUE THREAD

**Issue by scyto** [sdwilsh/brultech-serial2mqtt#119]
I am not sure I have formatted my config file correctly, i am trying to set a custom discovery prefix (which i use for all my MQTT based hass integrations)

The config.yaml is

```
#brultech-serial2mqtt_config
device:
  channels:
    - number: 32
  device_com: "COM1"
  name: "House Energy Monitor"
  url: "socket://192.168.1.98:8001"
mqtt:
  broker: "mqtt.mydomain.com"
  discovery_prefix: "hass-discovery"
```

The documentation implies this is the right location in the file?
https://github.com/sdwilsh/brultech-serial2mqtt#home-assistant

PS also confused about the channels - is that a list of channels or just the total number, for example if i am using all 32 channels should i list them all and give them all a name?

```
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__main__.py", line 6, in <module>
    bs2m = BrultechSerial2MQTT()
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 27, in __init__
    self._config = load_config()
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/config/__init__.py", line 80, in load_config
    valid_config: Dict[str, Any] = CONFIG_SCHEMA(raw_config)
  File "/usr/local/lib/python3.10/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/dist-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/dist-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['mqtt']['discovery_prefix']
s6-rc: info: service 99-ci-service-check: stopping
s6-rc: info: service 99-ci-service-check successfully stopped
s6-rc: info: service legacy-services: stopping
```

**Comment by scyto** [comment]
ok after a bunch of poke and hope based on reading the code i figured out the syntax for home assitaant section is like this.

```
# brultech-serial2mqtt_config
device:
  channels:
    - number: 32
  device_com: "COM2"
  name: "House Energy Monitor"
  url: "socket://192.168.1.98:8001"
mqtt:
  broker: "mqtt.mydomain.com"
  home_assistant:
    discovery_prefix: "hass-discovery"
```

**Comment by sdwilsh** [comment]
If you have any suggestions on how to make the docs more clear, I'd take a PR or leave a comment and I can address it :)
