### ISSUE TITLE
Is this tested and known to work with serial ECM-1240?

### ISSUE THREAD

**Issue by 42Network** [sdwilsh/brultech-serial2mqtt#214]
Just asking. I'm trying to get it to work and am getting some weird errors. I think it is failing for me on trying to set the date on my ECM-1240, which is an operation only supported on the GEM.

Is there a (perhaps undocumented) way to tell this integration I am using an ECM-1240, as opposed to a GEM in the config.yml file?

Thanks

**Comment by sdwilsh** [comment]
The underlying library will work with it, but I need to take in some updates.  There's some blocked dependencies due to the base image dropping 32-bit arm support as well as some home assistant stuff.  I'll be getting to it soon though!

**Comment by 42Network** [comment]
Ok. Anything I can do to offer to help? I know Python but not much about Github dependencies and PRs. I can certainly test for you on my ECM-1240's (I have four).

Also, it turns out the pip install for requirements-dev.txt was and still is hanging on compiling C code for dbus-fast, whatever that is. It pegs the RPi3 CPU "forever" at this point:
```
Building wheels for collected packages: dbus-fast
  Building wheel for dbus-fast (pyproject.toml) ... \
```
If I want to try to build it myself, do I need something beefier than an RPi3? This is the remote device I have by my circuit panel with a USB quad serial adapter connected to the four ECM-1240s.

Thanks

**Comment by 42Network** [comment]
Another observation, which may or may not be part of my ECM-1240 problem. When I run your docker container, the logs have several errors about "s6-test" missing. And indeed, there is no s6-test command I can find inside the docker container.

```
siobrultech_protocols.gem.protocol.ProtocolStateException: Expected state to be SENT_PACKET_DELAY_REQUEST, or RECEIVED_API_RESPONSE; but got SENT_API_REQUEST!
if: fatal: unable to spawn s6-test: No such file or directory
We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt
2023-10-25 20:47:21,728 - brultech_serial2mqtt - INFO - Setting up GEM device...
if: fatal: unable to spawn s6-test: No such file or directory
```
Thanks

**Comment by sdwilsh** [comment]
I haven't forgotten about this @42Network.  The first focus is getting the dependent library, https://github.com/sdwilsh/aiobrultech-serial, updated so I can cut a new release there.  Then I need to work through the failing builds and tests here to get all the dependencies updated.

> If I want to try to build it myself, do I need something beefier than an RPi3? This is the remote device I have by my circuit panel with a USB quad serial adapter connected to the four ECM-1240s.

I typically build on my amd64 machine.  I deploy this with a docker container, and you can cross-build on a more powerful machine, which is substantially easier!

> siobrultech_protocols.gem.protocol.ProtocolStateException: Expected state to be SENT_PACKET_DELAY_REQUEST, or RECEIVED_API_RESPONSE; but got SENT_API_REQUEST!

This was one of the big issues with the GEM vs the ECMs.  We need the updated library that has fixes for the ECM.

**Comment by sdwilsh** [comment]
There's a bit of a dependency tree here:
* https://github.com/sdwilsh/siobrultech-protocols, which supports the GEM and ECM thanks to @jkeljo
* https://github.com/sdwilsh/aiobrultech-serial, which depends on the above, and once updated should work with the ECM
* This repository, which depends on the above, and should also work with the ECM, although I suspect there's some code that assumes the GEM because it's all I have to test with.

**Comment by sdwilsh** [comment]
I was able to get a new release of https://github.com/sdwilsh/aiobrultech-serial cut tonight that has the update this needs.  This repo now also needs to love and care to get the ECM support :)

**Comment by sdwilsh** [comment]
I'm working in #208.  The image now builds with those changes, but I haven't tried to test it with my GEM yet.  In theory, you could build it and see if it works the ECM, but there's probably some changes that need to be made about the commands we send at startup.

**Comment by sdwilsh** [comment]
@42Network, I think the only blocker now is figuring out how to only do [this](https://github.com/sdwilsh/brultech-serial2mqtt/blob/main/brultech_serial2mqtt/__init__.py#L54) when we have a GEM, although there's a method or two in there that we probably want to call for an ECM as well.

**Comment by 42Network** [comment]
Hi. Thanks for the update. I see you have done quite a lot of work on it. I have just now tested it and it still doesn't work, but seems to no longer force check the time on my ECM, which is progress!

Here is my config.yml, with new type: ECM setting. I know the MQTT settings need to be updated but I'm just trying to get the serial connection to work first. Let me know if this looks correct.

```
---
device:
  channels:
    - number: 1
  device_com: "COM1"
  name: "House Energy Monitor"
  baud: 19200
  type: ECM
mqtt:
  broker: "mqtt.mybroker.com"
logging:
  level: debug
  logs:
    siobrultech_protocols: "debug"
```

Here is my docker-compose.yaml as well. Let me know if I've got anything messed up. I have a quad serial-to-USB cable and the ECM-1240 I am testing is on /dev/ttyUSB3, which docker hopefully maps to /dev/ttyUSB0 as specified.

```
---
services:
  brultech:
    container_name: "serial2mqtt"
    devices:
      - "/dev/ttyUSB3:/dev/ttyUSB0"
    image: "ghcr.io/sdwilsh/brultech-serial2mqtt:main"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/nathan/brultech-serial2mqtt:/config:ro"
```


 I have debug turned on and I see it tries to set the send interval on my ECM, but then somehow it still things the set fails. Log below:

```
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

chown: changing ownership of '/config': Read-only file system
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****
[custom-init] No custom files found, skipping...
[ls.io-init] done.
2023-12-03 01:54:38,477 - brultech_serial2mqtt - INFO - Setting up 0 device...
2023-12-03 01:54:38,477 - brultech_serial2mqtt - DEBUG - Setting the packet send interval on the device
2023-12-03 01:54:38,482 - siobrultech_protocols.gem.protocol - INFO - 281473349614928: Connection opened
2023-12-03 01:54:38,483 - siobrultech_protocols.gem.protocol - DEBUG - 281473349614928: Sending API request b'\xfc'...
2023-12-03 01:54:38,489 - siobrultech_protocols.gem.protocol - DEBUG - 281473349614928: Received 1 bytes
2023-12-03 01:54:38,490 - siobrultech_protocols.gem.protocol - DEBUG - 281473349614928: Sending API request b'SET'...
2023-12-03 01:54:38,505 - siobrultech_protocols.gem.protocol - DEBUG - 281473349614928: Received 1 bytes
2023-12-03 01:54:38,506 - siobrultech_protocols.gem.protocol - DEBUG - 281473349614928: Sending API request b'IV2'...
2023-12-03 01:54:38,522 - siobrultech_protocols.gem.protocol - DEBUG - 281473349614928: Received 1 bytes
2023-12-03 01:54:38,522 - siobrultech_protocols.gem.protocol - DEBUG - 281473349614928: Sending API request b'\x08'...
2023-12-03 01:54:38,537 - siobrultech_protocols.gem.protocol - DEBUG - 281473349614928: Received 1 bytes
2023-12-03 01:54:38,539 - siobrultech_protocols.gem.protocol - DEBUG - 281473349614928: Ended API request
2023-12-03 01:54:38,540 - siobrultech_protocols.gem.protocol - INFO - 281473349614928: Connection closed
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__main__.py", line 9, in <module>
    loop.run_until_complete(bs2m.start())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 55, in start
    await self._setup_device(device_connection)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 134, in _setup_device
    await connection.set_packet_send_interval(
  File "/usr/local/lib/python3.11/dist-packages/aiobrultech_serial/__init__.py", line 118, in set_packet_send_interval
    raise SetFailed()
aiobrultech_serial.exceptions.SetFailed
if: fatal: unable to spawn s6-test: No such file or directory

```

**Comment by sdwilsh** [comment]
> Is there a way to have the debug log show the contents of the bytes it received from the ECM?

By default, the library tries to connect to `/dev/ttyUSB0`.  You can configure `device.url` [with more options](https://pythonhosted.org/pyserial/url_handlers.html) to enable logging (I've not tried this, but it's supported by the underlying pyserial library).

I guess it's also worth verifying that the device is attached to `/dev/ttyUSB0`.

**Comment by 42Network** [comment]
I've confirmed that I can talk to my ECM from inside the docker container. I've isolated the problem to the code in the upstream library [siobrultech-protocols](https://github.com/sdwilsh/siobrultech-protocols/tree/main) where it seems the response from ECM is ignored after it successfully sets the PACKET_SEND_INTERVAL. I am pretty sure that since ecm_parser=None but the api calling routine is expecting some response, the SetFail exception is thrown. 

I also notice that in the tests for this ECM function in siobrultech-protocols, the output is ignored by the test routine. I don't know much about Python, but this seems to be incorrect.

```
SET_PACKET_SEND_INTERVAL = ApiCall[int, bool](
    gem_formatter=lambda si: f"{CMD_SET_PACKET_SEND_INTERVAL}{si:03}",
    gem_parser=NewlineTerminatedStringResponseParser(
        lambda response: response == "IVL\r\n"
    ),
    ecm_formatter=lambda si: [b"\xfc", b"SET", b"IV2", bytes([si])],
    ecm_parser=None,
)
```
[code](https://github.com/sdwilsh/siobrultech-protocols/blob/de4667a16fc1391df9ce148b96af82d4587dece8/siobrultech_protocols/gem/api.py#L145)

I'd like to test this further, but now I don't know how to make modifications to the upstream library correctly to test serial2mqtt using a local build. Any advice?

**Comment by 42Network** [comment]
Ok. So why does aiobrultech_serial.exceptions.SetFailed get thrown? I can see inside my ECM that the PACKET_SEND_INTERVAL was correctly set to 8 by your serial2mqtt. And I even changed the interval manually to another value (like 19) and I see serial2mqtt within a few seconds set it back to 8 but still throws the error in docker logs and won't proceed any further.

**Comment by 42Network** [comment]
Well, this is weird and curious. I temporarily commented out the call to set_packet_send_interval on line 133 of __init__.py and now I am receiving some serial data via MQTT. 
```
logger.debug("SKIP Setting the packet send interval on the device")
        #await connection.set_packet_send_interval(
        #    self._config.device.send_interval_seconds
        #)
```

I manually set the ECM send interval to 8 and toggled ON the ECM to send packets (using a modified version of btcfg.py, originally written in Python 2 years ago by Matt Wall that I got working in Python 3). 

So something is not working, in my case at least, with the serial2mqtt setup functions for the ECM-1240.

Here is the output of "docker logs serial2mqtt" showing some successful data published via MQTT after I bypassed the setup as mentioned above.

```
2023-12-05 03:40:15,047 - brultech_serial2mqtt - INFO - Published Home Assistant dicovery configuration for a sensor identified by gem_448_channel_7_energy to homeassistant/sensor/gem_448_channel_7_energy/config
2023-12-05 03:40:15,049 - brultech_serial2mqtt - DEBUG - Configuration for sensor identified by gem_448_channel_7_energy:
{'availability': [{'payload_available': 'online',
                   'topic': 'brultech-serial2mqtt-448/status'},
                  {'payload_not_available': 'offline',
                   'topic': 'brultech-serial2mqtt-448/status'}],
 'device': {'identifiers': ['brultech-serial2mqtt,serial-448',
                            'brultech-serial2mqtt,device_id-5'],
            'manufacturer': 'Brultech Research Inc.',
            'model': 'GreenEye Monitor',
            'name': 'House Energy Monitor'},
 'device_class': 'energy',
 'enabled_by_default': True,
 'name': 'House Energy Monitor Channel 7 Energy',
 'qos': 1,
 'state_class': 'total_increasing',
 'state_topic': 'brultech-serial2mqtt-448/state',
 'unique_id': 'gem_448_channel_7_energy',
 'unit_of_measurement': 'Wh',
 'value_template': '{{ (value_json.channel_7.absolute_watt_seconds / 3600) | '
                   'round }}'}
2023-12-05 03:40:15,052 - brultech_serial2mqtt - INFO - Published Home Assistant dicovery configuration for a sensor identified by gem_448_channel_7_power to homeassistant/sensor/gem_448_channel_7_power/config
2023-12-05 03:40:15,054 - brultech_serial2mqtt - DEBUG - Configuration for sensor identified by gem_448_channel_7_power:
{'availability': [{'payload_available': 'online',
                   'topic': 'brultech-serial2mqtt-448/status'},
                  {'payload_not_available': 'offline',
                   'topic': 'brultech-serial2mqtt-448/status'}],
 'device': {'identifiers': ['brultech-serial2mqtt,serial-448',
                            'brultech-serial2mqtt,device_id-5'],
            'manufacturer': 'Brultech Research Inc.',
            'model': 'GreenEye Monitor',
            'name': 'House Energy Monitor'},
 'device_class': 'power',
 'enabled_by_default': True,
 'name': 'House Energy Monitor Channel 7 Power',
 'qos': 1,
 'state_class': 'measurement',
 'state_topic': 'brultech-serial2mqtt-448/state',
 'unique_id': 'gem_448_channel_7_power',
 'unit_of_measurement': 'W',
 'value_template': '{{ value_json.channel_7.power }}'}
2023-12-05 03:40:15,057 - brultech_serial2mqtt - INFO - Notifying clients that we are online on brultech-serial2mqtt-448/status
```

Any further ideas?

**Comment by sdwilsh** [comment]
I wonder if @jkeljo has a newer firmware on the ECM that was tested, and that's the difference.  @42Network, what version of firmware are you running?

**Comment by 42Network** [comment]
The ECM-1240 I am testing is brand-new from Brultech and is running version 1.038. 

Based on the screenshot below, which shows the latest version for download from Brultech support is only 1.035, I suspect mine is actually a newer firmware than @jkeljo.

I have three other ECM-1240s that run 1.035. I can try your integration on one of those and report back tomorrow if my newer firmware is causing a problem.

![image](https://github.com/sdwilsh/brultech-serial2mqtt/assets/35043496/2e41b7a6-eebd-4016-8b88-59048beda13e)

**Comment by 42Network** [comment]
I'm sad to report the same issue with my 1.035 ECM-1240 device. The set send interval sequence is successfully sent to the ECM, but for some reason serial2mqtt immediately gets a SetFailed exception. 

```
2023-12-06 14:37:45,253 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-06 14:37:45,255 - brultech_serial2mqtt - INFO - Setting up 0 device...
2023-12-06 14:37:45,255 - brultech_serial2mqtt - DEBUG - Setting the packet send interval on the device
2023-12-06 14:37:45,259 - siobrultech_protocols.gem.protocol - INFO - 281473498314704: Connection opened
2023-12-06 14:37:45,261 - siobrultech_protocols.gem.protocol - DEBUG - 281473498314704: Sending API request b'\xfc'...
2023-12-06 14:37:45,275 - siobrultech_protocols.gem.protocol - DEBUG - 281473498314704: Received 1 bytes
2023-12-06 14:37:45,276 - siobrultech_protocols.gem.protocol - DEBUG - 281473498314704: Sending API request b'SET'...
2023-12-06 14:37:45,291 - siobrultech_protocols.gem.protocol - DEBUG - 281473498314704: Received 1 bytes
2023-12-06 14:37:45,292 - siobrultech_protocols.gem.protocol - DEBUG - 281473498314704: Sending API request b'IV2'...
2023-12-06 14:37:45,307 - siobrultech_protocols.gem.protocol - DEBUG - 281473498314704: Received 1 bytes
2023-12-06 14:37:45,308 - siobrultech_protocols.gem.protocol - DEBUG - 281473498314704: Sending API request b'\x08'...
2023-12-06 14:37:45,323 - siobrultech_protocols.gem.protocol - DEBUG - 281473498314704: Received 1 bytes
2023-12-06 14:37:45,325 - siobrultech_protocols.gem.protocol - DEBUG - 281473498314704: Ended API request
2023-12-06 14:37:45,326 - siobrultech_protocols.gem.protocol - INFO - 281473498314704: Connection closed
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__main__.py", line 9, in <module>
    loop.run_until_complete(bs2m.start())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 55, in start
    await self._setup_device(device_connection)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 134, in _setup_device
    await connection.set_packet_send_interval(
  File "/usr/local/lib/python3.11/dist-packages/aiobrultech_serial/__init__.py", line 118, in set_packet_send_interval
    raise SetFailed()
aiobrultech_serial.exceptions.SetFailed
```

**Comment by 42Network** [comment]
Is there perhaps an option c) leave ecm_parser undefined for this case? That way, when the protocol.py calls the has_parser method it will learn there is no ecm_parser and skip the parsing and just return True?

**Comment by sdwilsh** [comment]
I think that is still (b), but I might have misread the code (was looking on the bus ride in today on my phone; can look more closely when I'm home tonight).

**Comment by sdwilsh** [comment]
I need to cut a new release for `siobrultech-protocols`, bump that in `aiobrultech-serial`, cut a new release in `aiobrultech-serial`, and then bump that here.  Before I can do the first one, I want to get in https://github.com/sdwilsh/siobrultech-protocols/pull/237 because I technically changed the type of `temperatures` in the packet, even if it is semantically the same.

Once @jkeljo gets a chance to approve that PR, the releases should be quick to work through, so I expect us to new build for you soon that I hope will work.

You might be able to just pull down the updated source files in your container, but that's some hackery that I don't exactly suggest doing :)

**Comment by jkeljo** [comment]
> I technically changed the type of temperatures in the packet

Did you, though? I thought `Optional[X]` and `X | None` were entirely interchangeable (like you can pass one to the other without a typechecker getting mad.

**Comment by sdwilsh** [comment]
I know...pyright was unhappy with one but not the other.  I think they are the same, but pyright sure didn't.

**Comment by sdwilsh** [comment]
We've got two packets at the point this is throwing.  We collect one right away at the start here: https://github.com/sdwilsh/brultech-serial2mqtt/blob/main/brultech_serial2mqtt/__init__.py#L60

I think maybe we should add some verbose logging each time we get a packet maybe in order to figure out what's going on.  It's as if you aren't getting all the data.

> PS: I really appreciate your patience in working through this with me. Wish I could do more to help with the development. I've actually been hoping to eventually find a small portion of the HA codebase where I could learn enough Python and GitHub CI/CD skills to make a contribution to the Home Assistant ecosystem. If you guys can tolerate a newbie associate contributor on this serial2mqtt module I'd love to learn the ropes and help you, especially since I have 4 ECM-1240 devices for testing.

I largely re-learned Python for this project (last time I had used Python, was a long time ago, and it was Python 2), so I can sympathize!  Happy to help out, although my availability can be intermittent at times as I have, arguably, too many projects.

> One enhancement I'd like to help make is to support multiple ECM-1240 from a single container. As it is now, I would have to run four containers on my little RPi 3 to get data from my 4 ECMs, and I fear 4 docker containers might kill the RPi.

It's worth noting that I'd like to move to a distroless setup, which will result in much less heavy containers.  I can try to document my plan there this weekend.

> Can I open some "Issues" for the above enhancement ideas?

Sure thing!  Without an ECM, I'm not going to build the additional support out, but happy to work through how to add it here.

**Comment by jkeljo** [comment]
> I'd also like the capability to send less-frequent MQTT data to HA (which you currently support via the skip_packets optional parameter) but more frequent data directly to InfluxDB.

As an implementation idea, hacs-greeneye-monitor does this on the HA side. The energy sensors are throttled to a real slow update rate (once every 30 mins I think? Don't remember exactly) and the others update every time a packet comes in but are disabled by default. Users can then set up the influxDB plugin/integration, enable those sensors, and configure HA to send them to influx instead of recorder.

**Comment by 42Network** [comment]
I see the new container with debug logging of packets received, but I guess python doesn't know how to pretty print the packets:

```
2023-12-08 22:22:22,728 - brultech_serial2mqtt - INFO - Notifying clients that we are online on brultech-serial2mqtt-18131/status
2023-12-08 22:22:30,550 - siobrultech_protocols.gem.protocol - DEBUG - 281473680546512: Received 18 bytes
2023-12-08 22:22:30,551 - siobrultech_protocols.gem.protocol - DEBUG - 281473680546512: Not enough data in buffer yet (18 bytes)
2023-12-08 22:22:30,566 - siobrultech_protocols.gem.protocol - DEBUG - 281473680546512: Received 28 bytes
2023-12-08 22:22:30,567 - siobrultech_protocols.gem.protocol - DEBUG - 281473680546512: Not enough data in buffer yet (46 bytes)
2023-12-08 22:22:30,582 - siobrultech_protocols.gem.protocol - DEBUG - 281473680546512: Received 19 bytes
2023-12-08 22:22:30,584 - siobrultech_protocols.gem.protocol - DEBUG - 281473680546512: Parsed one ECM-1240 packet.
2023-12-08 22:22:30,585 - brultech_serial2mqtt - DEBUG - Received new packet:
<siobrultech_protocols.gem.packets.Packet object at 0xffffb2a41e10>
2023-12-08 22:22:30,592 - siobrultech_protocols.gem.protocol - INFO - 281473680546512: Connection closed
```

**Comment by sdwilsh** [comment]
That's what I get for not testing and assuming it'd work...

https://github.com/sdwilsh/siobrultech-protocols/issues/239 would fix that, but let's get something sooner by just logging the string.

**Comment by 42Network** [comment]
Nice. I see the packets now as strings. Curiously, even though the DEBUG log says it "parsed one ECM-1240" packet, the string printed is missing the Aux 1-5 channels, which would be the case for the older, more basic ECM-1220 model.

What do you make of this clue? Do you need to provide a way for me to tell serial2mqtt the device type is ECM-1240 versus an ECM-1220 in the config.yaml?

```
2023-12-09 03:35:11,313 - siobrultech_protocols.gem.protocol - DEBUG - 281473659550800: Received 8 bytes
2023-12-09 03:35:11,314 - siobrultech_protocols.gem.protocol - DEBUG - 281473659550800: Not enough data in buffer yet (8 bytes)
2023-12-09 03:35:11,329 - siobrultech_protocols.gem.protocol - DEBUG - 281473659550800: Received 27 bytes
2023-12-09 03:35:11,330 - siobrultech_protocols.gem.protocol - DEBUG - 281473659550800: Not enough data in buffer yet (35 bytes)
2023-12-09 03:35:11,345 - siobrultech_protocols.gem.protocol - DEBUG - 281473659550800: Received 28 bytes
2023-12-09 03:35:11,345 - siobrultech_protocols.gem.protocol - DEBUG - 281473659550800: Not enough data in buffer yet (63 bytes)
2023-12-09 03:35:11,361 - siobrultech_protocols.gem.protocol - DEBUG - 281473659550800: Received 2 bytes
2023-12-09 03:35:11,362 - siobrultech_protocols.gem.protocol - DEBUG - 281473659550800: Parsed one ECM-1240 packet.
2023-12-09 03:35:11,364 - brultech_serial2mqtt - DEBUG - Received new packet:
{"device_id": 2, "serial_number": 18131, "seconds": 4493634, "voltage": 124.9, "absolute_watt_seconds": [4363539969, 2829517594], "polarized_watt_seconds": [4150945108, 2509084942], "currents": [0.13, 0.07], "pulse_counts": [], "temperatures": [], "time_stamp": "2023-12-09T03:35:11.362631"}
2023-12-09 03:35:11,370 - siobrultech_protocols.gem.protocol - INFO - 281473659550800: Connection closed
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__main__.py", line 9, in <module>
    loop.run_until_complete(bs2m.start())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 111, in start
    await device_manager.handle_new_packet(packet, mqtt_client)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/device/__init__.py", line 27, in handle_new_packet
    await asyncio.gather(
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/device/channel.py", line 239, in handle_new_packet
    await asyncio.gather(*updates)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/device/channel.py", line 27, in handle_new_packet
    self._average_power = self._last_packet.get_average_power(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/siobrultech_protocols/gem/packets.py", line 165, in get_average_power
    index, oldest_packet.absolute_watt_seconds[index]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

**Comment by sdwilsh** [comment]
> Do you need to provide a way for me to tell serial2mqtt the device type is ECM-1240 versus an ECM-1220 in the config.yaml?

I didn't think that's the issue, however, as it thinks it is an ECM-1240, as you noted:
```
Parsed one ECM-1240 packet
```

This might actually be a red herring, as `aux` and `dc_voltage` are missing from the `__str__` method: https://github.com/sdwilsh/siobrultech-protocols/blob/68078bce3057632d6660d43fd82bd9125e38298c/siobrultech_protocols/gem/packets.py#L68-L82

**Comment by sdwilsh** [comment]
@42Network, can you share the config you are using right now too?  Seeing that packet have only two channels of data, but then in #238, there are three makes me think that could ultimately be the cause of the exception.

**Comment by 42Network** [comment]
It is still the same, with just three channels for now, first two being net capable and third being Aux 1. 

```
---
device:
  name: "House Energy Monitor Three"
  baud: 19200
  type: ECM
  device_com: "COM1"
  channels:
    - number: 1
      name: "ChanOne"
    - number: 2
      name: "ChanTwo"
    - number: 3
      name: "ChanThree"
mqtt:
  broker: "10.1.1.100"
  username: mqtt
  password: mqtt
    #client_id: bt-serial-3
    #topic_prefix: btserial3
  home_assistant:
    skip_packets: 10
logging:
  level: debug
  logs:
    siobrultech_protocols: "debug"
    aiobrultech_serial: "debug"
    asyncio: "debug"

```

**Comment by sdwilsh** [comment]
So that's probably the issue here; we don't have any logic to read from `aux` channels right now in this repo (it's not something the GEM supported), so you really just have two usable channels at the moment.  I think if you drop the third channel from your configuration, you'll be able to get data for the other two, at least.

I guess your first project might be to add support for aux data channels, since I can't really test this without an ECM myself.

Aside, I'm working on a PR right now to at least log the case where a channel is not able to be configured like this so it's not an error (but will be skipped and logged as an error).

**Comment by 42Network** [comment]
> So that's probably the issue here; we don't have any logic to read from `aux` channels right now in this repo (it's not something the GEM supported), so you really just have two usable channels at the moment. I think if you drop the third channel from your configuration, you'll be able to get data for the other two, at least.
> 
> I guess your first project might be to add support for aux data channels, since I can't really test this without an ECM myself.
> 
> Aside, I'm working on a PR right now to at least log the case where a channel is not able to be configured like this so it's not an error (but will be skipped and logged as an error).

Interesting. Does only serial2mqtt need to be retrofit to support aux, or do  aiobrultech_serial and siobrultech_protocols need to be updated as well?

And indeed, with your latest rev, I am getting MQTT data now, but only on the 2 main channels.

**Comment by sdwilsh** [comment]
Luckily, it's just modifying this repository, which should keep the complexity down (unless we find any bugs).  I filed #246 to outline the scope of work needed to support the auxiliary channels on the ECM.

**Comment by 42Network** [comment]
Ok. We can take the ECM Aux conversation over to #246. 

I think this means we can close this issue #214 itself. And then if/when I find other problems with the code on my ECM I can open other issues? Do you agree?
