### ISSUE TITLE
Exception causes permanent disconnection

### ISSUE THREAD

**Issue by sdwilsh** [sdwilsh/brultech-serial2mqtt#27]
```
Task exception was never retrieved
future: <Task finished name='Task-95' coro=<BrultechSerial2MQTT._publish_home_assistant_discovery_config.<locals>.subscribe_to_home_assistant_birth() done, defined at /src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py:126> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 134, in subscribe_to_home_assistant_birth
    async for message in messages:  # type: ignore https://github.com/sbtinstruments/asyncio-mqtt/pull/87
  File "/usr/local/lib/python3.8/dist-packages/asyncio_mqtt/client.py", line 342, in _message_generator
    raise MqttError("Disconnected during message iteration")
asyncio_mqtt.error.MqttError: Disconnected during message iteration
2021-12-24 15:22:23,659 - brultech_serial2mqtt.device - ERROR - Exception caught while attempting to publish a packet!
Traceback (most recent call last):
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/device/__init__.py", line 33, in handle_new_packet
    await self._publish_packet(packet, mqtt_client)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/device/__init__.py", line 49, in _publish_packet
    await mqtt_client.publish(
  File "/usr/local/lib/python3.8/dist-packages/asyncio_mqtt/client.py", line 237, in publish
    raise MqttCodeError(info.rc, "Could not publish message")
```

The logs will then fill up with this:
```
asyncio_mqtt.error.MqttCodeError: [code:4] Could not publish message
2021-12-24 15:22:31,665 - brultech_serial2mqtt.device - ERROR - Exception caught while attempting to publish a packet!
Traceback (most recent call last):
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/device/__init__.py", line 33, in handle_new_packet
    await self._publish_packet(packet, mqtt_client)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/device/__init__.py", line 49, in _publish_packet
    await mqtt_client.publish(
  File "/usr/local/lib/python3.8/dist-packages/asyncio_mqtt/client.py", line 237, in publish
    raise MqttCodeError(info.rc, "Could not publish message")
```

1) we probably want a health check to make sure mqtt is connected
2) we should get to the bottom of this error

**Comment by sdwilsh** [comment]
(1) is actually hard because the underlying library doesn't expose the connection state, alas.

**Comment by sdwilsh** [comment]
The docker container now restarts if it gets killed, which mitigates this issue enough that I don't care to fix it.
