### ISSUE TITLE
Minimum System Requirements

### ISSUE THREAD

**Issue by david81** [sdwilsh/brultech-serial2mqtt#93]
Sorry to add this as an issue, but I'm not aware of a better way to ask this. Do you know what the min system requirements for this would be? Would a RPi 1B get bogged down by the volume or be a limiting factor?

**Comment by sdwilsh** [comment]
If you ran it without docker, you might be able to make it work, but that's not trivial (but certainly doable).  I run it in an ubuntu container, and it looks like that only supports as low as a RPi 2.

**Comment by sdwilsh** [comment]
Thinking about this a bit more, @david81, if you can get the dependencies installed and python installed, I don't see why this wouldn't work.  The program itself isn't very resource intensive, and you can tune it to be even less so.

**Comment by david81** [comment]
I appreciate that. I may just give it a try. Just ordered the GEM so it may be a bit before it's all up and running.

**Comment by sdwilsh** [comment]
I'll leave this open in case any issues come out of it then!

**Comment by david81** [comment]
Thank you sir. I was able to get this installed via pip but don't have my GEM yet, so not sure if it'll work. While I wait, do you happen to know if there is a benefit to using the RPi onboard serial (via GPIO) vs a USB adapter?

**Comment by sdwilsh** [comment]
I mounted the Pi in a DIN case, and used USB because I wanted a cleaner
look.  I can dig up the parts I ordered on Amazon if you are interested.

**Comment by david81** [comment]
Thanks. I don't think a parts list is needed. I may try the GPIO route for fun. GEM is supposed to be delivered next week, so I should be able to run a test shortly thereafter.

**Comment by awbn** [comment]
Note that if you do go the GPIO route, you'll need to use something like a MAX3232 level translator or an rs232 hat. The serial GPIO pins on the pi are not 5v tolerant (i.e., are serial TTL pins) and don't like the rs232 ~5v levels that the GEM outputs. Ask me how I learned 😠 

FWIW, this project does run smoothly under docker on a pi 2 (with a USB to serial adapter)

**Comment by david81** [comment]
Well, I finally had a chance to give this a go while trying to troubleshooting my DashBox connection issues. The Pi is hooked up via USB->Serial (I needed it for debugging purposes anyway). When attempting to run this sans Docker, I'm getting the following output

`
/src/brultech_serial2mqtt/brultech_serial2mqtt/__main__.py:7: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(bs2m.start())
2022-11-21 00:41:04,246 - brultech_serial2mqtt - INFO - Setting up GEM device...
2022-11-21 00:41:04,262 - siobrultech_protocols.gem.protocol - INFO - 3048224032: Connection opened
2022-11-21 00:41:04,271 - siobrultech_protocols.gem.protocol - DEBUG - 3048224032: Starting API request. Requesting packet delay...
2022-11-21 00:41:04,280 - siobrultech_protocols.gem.protocol - DEBUG - 3048224032: Received 1 bytes
2022-11-21 00:41:04,285 - siobrultech_protocols.gem.protocol - DEBUG - 3048224032: No header found. Discarding junk data: bytearray(b'\x82')
'...-11-21 00:41:07,284 - siobrultech_protocols.gem.protocol - DEBUG - 3048224032: Sending API request '^^^SYSDTM22,11,21,00,41,07
2022-11-21 00:41:07,308 - siobrultech_protocols.gem.protocol - DEBUG - 3048224032: Received 8 bytes
2022-11-21 00:41:10,300 - siobrultech_protocols.gem.protocol - INFO - 3048224032: Connection closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/api.py", line 88, in call_api
    yield send
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/api.py", line 128, in set_date_and_time
    return await f(time)
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/api.py", line 83, in send
    return api.receive_response(protocol)
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/api.py", line 70, in receive_response
    return self._parse_response(protocol.receive_api_response())
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/protocol.py", line 296, in receive_api_response
    response = bytes(self._api_buffer).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__main__.py", line 7, in <module>
    asyncio.get_event_loop().run_until_complete(bs2m.start())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 50, in start
    await self._setup_gem(device_connection)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 114, in _setup_gem
    await connection.synchronize_time()
  File "/usr/local/lib/python3.10/site-packages/aiobrultech_serial/__init__.py", line 117, in synchronize_time
    success = await api.synchronize_time(self._protocol)
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/api.py", line 168, in synchronize_time
    return await set_date_and_time(protocol, time, serial_number)
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/api.py", line 127, in set_date_and_time
    async with call_api(SET_DATE_AND_TIME, protocol, serial_number) as f:
  File "/usr/local/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/api.py", line 90, in call_api
    protocol.end_api_request()
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/protocol.py", line 307, in end_api_request
    self._expect_state(
  File "/usr/local/lib/python3.10/site-packages/siobrultech_protocols/gem/protocol.py", line 327, in _expect_state
    raise ProtocolStateException(actual=self._state, expected=expected_state)
siobrultech_protocols.gem.protocol.ProtocolStateException: Expected state to be SENT_PACKET_DELAY_REQUEST, or RECEIVED_API_RESPONSE; but got SENT_API_REQUEST!
`
I am able to use the dump.py example from aiobrultech-serial to dump put the packets successfully, so I know the packets are getting there and can be read. 

I'm sure it's something I've done while attempting to get this running outside of Docker that is causing my issue, but I'm not quite sure what, at this point. I'll keep digging, but if you've got any ideas on where to look, I appreciate it.

**Comment by david81** [comment]
In the end, I decided to go another direction with my integration (for now). Inspired by this project, I just created a simple Node-Red flow that listens for binary packets forwarded by the DashBox then translates them to MQTT messages. The code here gave me some hints on getting everything up and running. My GEM data is now happily streaming to HA and available via the Energy dashboard.

**Comment by sdwilsh** [comment]
>  I am able to use the dump.py example from aiobrultech-serial to dump put the packets successfully, so I know the packets are getting there and can be read.

That's really odd, because I'm pretty sure the code is the same in this and in `dump.py` :(

Glad you got something working!
